package com.example.ui.theme

enum class AppLanguage {
    ENGLISH,
    HINDI
}

object AppStrings {
    private val en = mapOf(
        "app_name" to "SAHAKAAR SETU",
        "tagline" to "Trusted Skills. Fair Work. Stronger Communities.",
        "operating_system" to "Digital Operating System for Labour Cooperatives",
        "book_service" to "Book a Service",
        "join_worker" to "Join as Worker",
        "for_institutions" to "Institutional Bulk Hiring",
        "emergency_service" to "Emergency 24x7",
        "verified_worker" to "VERIFIED WORKER",
        "skill_passport" to "Skill Passport",
        "cooperative_control" to "Cooperative Control Centre",
        "fair_distribution" to "Equitable Job Distribution",
        "welfare_wallet" to "Welfare Wallet",
        "live_map" to "Live Worker Map",
        "ai_classifier" to "AI Service Recognition",
        "demand_forecast" to "Workforce Intelligence",
        "describe_problem" to "Describe what needs repair or speak problem...",
        "speak_voice" to "Voice Input",
        "listening" to "Listening...",
        "ai_classified_badge" to "AI Recognized Service",
        "recommended_workers" to "Recommended Cooperative Workers",
        "match_score" to "Match Score",
        "active_bookings" to "Active Bookings",
        "quick_actions" to "Quick Actions",
        "emergency_banner" to "🚨 Need Urgent Assistance? Connect in < 15 mins",
        "cooperative" to "Cooperative",
        "available" to "Available",
        "busy" to "On Duty",
        "offline" to "Offline",
        "on_the_way" to "Assigned",
        "arrived" to "Arrived",
        "work_started" to "In Progress",
        "completed" to "Completed",
        "pay_now" to "Pay Now",
        "view_invoice" to "View Invoice",
        "rate_service" to "Rate & Review",
        "raise_dispute" to "Raise Dispute",
        "demo_notice" to "Secure Payment via UPI or Cash on Service Completion",
        "total_workers" to "Total Workers",
        "verified_workers" to "Verified Workers",
        "jobs_today" to "Jobs Today",
        "revenue" to "Cooperative Revenue",
        "worker_utilization" to "Worker Utilization",
        "average_rating" to "Average Rating",
        "federation" to "Federation Dashboard",
        "switch_role" to "Switch Profile"
    )

    private val hi = mapOf(
        "app_name" to "सहकार सेतु",
        "tagline" to "विश्वसनीय हुनर। सम्मानजनक काम। सशक्त समुदाय।",
        "operating_system" to "श्रम सहकारी समितियों का डिजिटल ऑपरेटिंग सिस्टम",
        "book_service" to "कारीगर बुक करें",
        "join_worker" to "कारीगर के रूप में जुड़ें",
        "for_institutions" to "संस्थागत थोक भर्ती",
        "emergency_service" to "आपातकालीन 24x7 सेवा",
        "verified_worker" to "प्रमाणित श्रमिक (सहकारी सत्यापित)",
        "skill_passport" to "डिजिटल स्किल पासपोर्ट",
        "cooperative_control" to "सहकारी नियंत्रण केंद्र",
        "fair_distribution" to "समान कार्य आवंटन",
        "welfare_wallet" to "कल्याण कोष बटुआ",
        "live_map" to "लाइव कारीगर नक्शा",
        "ai_classifier" to "एआई सेवा पहचान",
        "demand_forecast" to "श्रम शक्ति विश्लेषण",
        "describe_problem" to "अपनी समस्या बताएं या बोलकर दर्ज करें...",
        "speak_voice" to "आवाज़ से बताएं",
        "listening" to "सुन रहे हैं...",
        "ai_classified_badge" to "एआई द्वारा पहचानी गई सेवा",
        "recommended_workers" to "सुझाए गए सहकारी कारीगर",
        "match_score" to "मिलान स्कोर",
        "active_bookings" to "सक्रिय बुकिंग",
        "quick_actions" to "त्वरित कार्य",
        "emergency_banner" to "🚨 तत्काल कारीगर चाहिए? 15 मिनट में पहुंचेगा",
        "cooperative" to "सहकारी समिति",
        "available" to "उपलब्ध",
        "busy" to "कार्यरत",
        "offline" to "ऑफलाइन",
        "on_the_way" to "आबंटित (Assigned)",
        "arrived" to "पहुंच गए",
        "work_started" to "कार्य प्रारंभ",
        "completed" to "सम्पन्न हुआ",
        "pay_now" to "भुगतान करें",
        "view_invoice" to "रसीद देखें",
        "rate_service" to "रेटिंग और समीक्षा",
        "raise_dispute" to "शिकायत दर्ज करें",
        "demo_notice" to "सुरक्षित भुगतान: यूपीआई अथवा कार्य समाप्ति पर नकद",
        "total_workers" to "कुल कारीगर",
        "verified_workers" to "सत्यापित कारीगर",
        "jobs_today" to "आज के कार्य",
        "revenue" to "सहकारी आय",
        "worker_utilization" to "कारीगर उपयोगिता",
        "average_rating" to "औसत रेटिंग",
        "federation" to "महासंघ डैशबोर्ड",
        "switch_role" to "प्रोफ़ाइल बदलें"
    )

    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.HINDI) hi else en
        return dict[key] ?: en[key] ?: key
    }
}
